### PR TITLE
#161967100 User view following and followers

### PR DESCRIPTION
**Pull request by Darius-Ndubi**
**What does this PR do?**
 - Allow user to see who they are following and who is following them

**Description of tasks to be completed?**
 - Allow users to view followers and following users on their profile

**How should this be manually tested?**
- Clone the repo and cd into the project root folder
- Switch to the relevant branch `git checkout ft-user-follow-unfollow-161967100`
- Run `npm install` to update your packages.
- Run tests with `npm test`

**What are the relevant pivotal tracker stories?**
[#161967100](https://www.pivotaltracker.com/story/show/161967100)

**ScreenShots**

### CODE REVIEW

**Review by denomash — CHANGES_REQUESTED** [review]
I have realised that view followers and following feature is overriding view profile, edit profile and view stats feature. Kindly fix that. I can give a hand.

**Comment by Darius-Ndubi** [comment]
@denomash That seams to be a bug let me handle it. Will get back to you when it is fixed.

**Review by denomash — APPROVED** [review]
👍

**Review by davishooly — APPROVED** [review]
👍

**Pull request merged**
