### PR TITLE
#163017419 link TravisCI with slack

### PR DESCRIPTION
**Pull request by davishooly**
#### What does this PR do?

- Link TravisCI with slack

#### Description of Task to be completed?

- When there is activity on TravisCI, updates automatically show up in a dedicated Slack channel (separate from the team channel)

#### What are the relevant pivotal tracker stories?
[#163017419](https://www.pivotaltracker.com/story/show/163017419)

### CODE REVIEW

**Review by Bryan-Cee — APPROVED** [review]
👍 LGTM

**Review by bettblake08 — APPROVED** [review]
👍

**Review by Darius-Ndubi — APPROVED** [review]
👍

**Comment by justmesam** [comment]
LGTM.    👍

**Pull request merged**
