### PR TITLE
#161967106 list bookmarked articles

### PR DESCRIPTION
**Pull request by denomash**
#### What does this PR do?

- List Bookmarked articles

#### Description of Task to be completed?

-  An authenticated user should be able to see all his bookmarked articles in his/her profile and navigate to them

#### How should this be manually tested?

- Clone this repo from the terminal

```
git clone https://github.com/andela/ah-code-titans-frontend.git
```

- cd into the projects folder
```
cd ah-code-titans-frontend
```

- Then Run `git fetch ft-list-bookmarked-articles-161967106` 

- checkout the branch: `git checkout ft-list-bookmarked-articles-161967106`

- Install all dependencies by running: `npm install` or `yarn`

- Run the app by running: `npm start`

#### What are the relevant pivotal tracker stories?
[#161967106](https://www.pivotaltracker.com/story/show/161967106)

**Checklist**

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] My changes generate no new warnings

####Screenshot
**WHEN A USER HAS NOT BOOKMARKED ANY ARTICLE**
screenshot 2019-02-06 at 13 44 36

**WHEN A USER HAS BOOKMARKED ARTICLES**
screenshot 2019-02-06 at 13 46 21

### CODE REVIEW

**Review by Darius-Ndubi — APPROVED** [review]
👍

**Review by davishooly — APPROVED** [review]
👍

**Review by Bryan-Cee — APPROVED** [review]
👍 LGTM

**Review by justmesam — APPROVED** [review]

**Review by bettblake08 — APPROVED** [review]
👍

**Pull request merged**
