### PR TITLE
#161967099 Users should be able to share articles on social media and via email

### PR DESCRIPTION
**Pull request by jillo-abdullahi**
**What does this PR do?**
-  Implements user ability to share articles on social media and via email.

**Description of tasks to be completed?**
- Authenticated users can share articles on social media as well as via email.

**How should this be manually tested?**

- Clone the repo and cd into the project folder
- Switch to the appropriate branch with `ft-share-article-161967099`
- Run `npm install` to update your packages.
- Run tests with `npm test`
- Specify the domain you are running the app from with `export REACT_APP_API="https://ah-codetitans-staging.herokuapp.com/"`
- Fire up the server with `npm start`
- Login to the app.
- Navigate to `/create_article` and post a new article.
- Once the single article loads, click on the share buttons to share.

**What are the relevant pivotal tracker stories?**
- [#161967099](https://www.pivotaltracker.com/story/show/161967099)

**Checklist (edited)**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Screenshots**

screenshot 2019-01-30 at 19 09 26

screenshot 2019-01-30 at 19 09 50

screenshot 2019-01-30 at 19 10 07

screenshot 2019-01-30 at 19 10 20

screenshot 2019-01-30 at 19 10 49

### CODE REVIEW

**Review by bettblake08 — APPROVED** [review]
👍

**Review by denomash — APPROVED** [review]
👍

**Review by Bryan-Cee — APPROVED** [review]
👍 LGTM

**Review by Darius-Ndubi — APPROVED** [review]

**Review by justmesam — CHANGES_REQUESTED** [review]
Why do we have other changes not related to the story on this PR?

**Comment by jillo-abdullahi** [comment]
@justmesam It took a while to merge my previous PR, so I had to branch off my previous update-delete branch. That's why you see changes from my other branch on this one as well.

**Review by justmesam — APPROVED** [review]

**Pull request merged**
