### PR TITLE
fix rating and comments error

### PR DESCRIPTION
**Pull request by denomash**
#### What does this PR do?

- Fix rating and comments bug.

#### Description of Task to be completed?

-  a user can rate an article successfully.
-  a user can edit comment an article.

#### How should this be manually tested?

- Clone this repo from the terminal

```
git clone https://github.com/andela/ah-code-titans-frontend.git
```

- cd into the projects folder
```
cd ah-code-titans-frontend
```

- Then Run `git fetch bg-bug-fix` 

- checkout the branch: `git checkout bg-bug-fix`

- Install all dependencies by running: `npm install` or `yarn`

- Run the app by running: `npm start`

**Checklist**

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] My changes generate no new warnings

####Screenshot

### CODE REVIEW

**Review by jillo-abdullahi — COMMENTED** [review]
👍

**Review by davishooly — APPROVED** [review]

**Review by bettblake08 — APPROVED** [review]
👍

**Review by jillo-abdullahi — APPROVED** [review]
LGTM 👍

**Review by bettblake08 — APPROVED** [review]
👍

**Review by Bryan-Cee — APPROVED** [review]
👍

**Review by Darius-Ndubi — APPROVED** [review]
👍

**Pull request merged**
